ACTIVITY_CODES = {
    # Daily Activities (D)
    "D01": "Walking slowly",
    "D02": "Walking quickly",
    "D03": "Jogging slowly",
    "D04": "Jogging quickly",
    "D05": "Walking upstairs and downstairs slowly",
    "D06": "Walking upstairs and downstairs quickly",
    "D07": "Sit (half chair) slowly → wait → stand slowly",
    "D08": "Sit (half chair) quickly → wait → stand quickly",
    "D09": "Sit (low chair) slowly → wait → stand slowly",
    "D10": "Sit (low chair) quickly → wait → stand quickly",
    "D11": "Sit → attempt to stand → collapse into chair",
    "D12": "Sit → lie slowly → wait → sit again",
    "D13": "Sit → lie quickly → wait → sit again",
    "D14": "Supine → lateral → wait → supine",
    "D15": "Standing → bend knees slowly → stand up",
    "D16": "Standing → bend (no knees) → stand up",
    "D17": "Enter car → sit → exit car",
    "D18": "Stumble while walking",
    "D19": "Gentle jump (no fall)",

    # Falls (F)
    "F01": "Forward fall (slip while walking)",
    "F02": "Backward fall (slip while walking)",
    "F03": "Lateral fall (slip while walking)",
    "F04": "Forward fall (trip while walking)",
    "F05": "Forward fall (trip while jogging)",
    "F06": "Vertical fall (fainting while walking)",
    "F07": "Fall with hand support on table (fainting)",
    "F08": "Forward fall while getting up",
    "F09": "Lateral fall while getting up",
    "F10": "Forward fall while sitting down",
    "F11": "Backward fall while sitting down",
    "F12": "Lateral fall while sitting down",
    "F13": "Forward fall while sitting (faint/sleep)",
    "F14": "Backward fall while sitting (faint/sleep)",
    "F15": "Lateral fall while sitting (faint/sleep)"
}